version: "3"

services: 
  digdag:
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes: 
      - ./project:/work
    ports:
      - 65432:65432
    command: /bin/sh -c "while sleep 1000; do :; done"
