apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digdag-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/affinity: 'cookie'
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: digdag-service
              port:
                number: 65432