name: Call a reusable workflow

on: [push]

jobs:

  call-workflow-passing-data:
    runs-on: ubuntu-latest
    uses: greatestgoat/mystudy/.github/workflows/workflow-B.yml@issue31
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}