name: Call a reusable workflow

on: [push]

jobs:

  call-workflow-passing-data:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/workflow-B.yml@greatestgoat/issue31
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}