name: output-file
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: Download output
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-log-file