name: check-secret
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: Check secret
    steps:
      - name: Retrieve secret
        env:
          secret_test: ${{ secrets.SECRET_TEST }}
        run: echo "$secret_test"